### ISSUE TITLE
HACKER ALERT

### ISSUE THREAD

**Issue by devraza** [Haider-Mirza/Spinter#3]
GUYS THIS MAN IS A HACKER DONT STAR HIS REPOS AND DONT FOLLOW HIM

HE DOES SUSSY THINGS WITH HIS TAILS USB AND USES KALI

**Comment by Haider-Mirza** [comment]
Hello, If you don't know this repo has 2 stars. Me and Me. Nobody would ever find out.
Anyway, this doesnt seem like a appropriate issue. Therefore, Please close this before I am forced to do so MYSELF >:(
