### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by devraza** [Haider-Mirza/Spinter#4]
It's open-source code, and not having a license voids the right for people to contribute or modify the code in any way.

**Comment by Haider-Mirza** [comment]
Bruv, it's not even close to usage. I haven't had the time to hack on it.

**Comment by devraza** [comment]
@Haider-Mirza but the README falsely claims that the code is licensed under the GNU GPL v3.

**Comment by Haider-Mirza** [comment]
Fixed!
